#!/bin/bash -ex

filename=${1%.pdf}

if [[ ! -f "$filename.pdf" ]]; then
    echo "Error '$filename.pdf' does not exist"
    exit -1
fi

if [[ ! -d pdfimages ]]; then
    mkdir pdfimages
fi

pdftoppm -scale-to-x 1920 -scale-to-y 1080 -png "$filename.pdf" "pdfimages/$filename"
